baseurl = "https://shubhxms.github.io"
languageCode = "en-us"
title = "shubham s."
sectionPagesMenu = "main"
pluralizelisttitles = false

[permalinks]
  pages = '/:title'

[markup.goldmark.renderer]
unsafe= true

  
[params]
relativeURLs = true
contentdir = "content"
mobileFriendly = true
fontFamily = "Podkova"
fontLink = "https://fonts.googleapis.com/css2?family=Caveat&family=Cormorant&family=Podkova&display=swap"
themeColor = "#3877ff"
backgroundColor = "#f2f6f7"
specialColor = "#006fff"


[menu]

[[menu.pages]]
  name = 'about'
  url = '/'
  weight = 1

[[menu.pages]]
  name = 'craft'
  url = '/craft'
  weight = 2

[[menu.pages]]
  name = 'now'
  url = '/now'
  weight = 3

[[menu.pages]]
  name = 'pins'
  url = 'https://aaranya.vercel.app'
  weight = 4

[[menu.pages]]
  name = 'blog'
  url = '/blog'
  weight = 5

[[menu.pages]]
  name = 'shelf'
  url = '/shelf'
  weight = 6

