baseurl = "/"
languageCode = "en-us"
title = "collison"
sectionPagesMenu = "main"
pluralizelisttitles = false

[permalinks]
  pages = '/:title'

[params]
relativeURLs = true
contentdir = "content"
mobileFriendly = true
fontFamily = "Helvetica"
fontLink = "https://fonts.googleapis.com/css2?family=Didact+Gothic&family=Vesper+Libre:wght@400;500;700&display=swap"
themeColor = "#e30f00"
backgroundColor = "#ffffff"
specialColor = "darkblue"


[menu]
[[menu.pages]]
  name = 'About'
  url = '/about'

[[menu.pages]]
  name = 'Advice'
  url = '/advice'

[[menu.pages]]
  name = 'Blog'
  url = '/blog'

[[menu.pages]]
  name = 'Bookshelf'
  url = '/bookshelf'

[[menu.pages]]
  name = 'Culture'
  url = '/culture'

[[menu.pages]]
  name = 'Links'
  url = '/links'

[[menu.pages]]
  name = 'People'
  url = '/people'

[[menu.pages]]
  name = 'Fast'
  url = '/fast'

[[menu.pages]]
  name = 'Pollution'
  url = '/pollution'

[[menu.pages]]
  name = 'Progress'
  url = '/progress'

[[menu.pages]]
  name = 'Questions'
  url = '/questions'

[[menu.pages]]
  name = 'Work'
  url = '/work'
