baseurl = "https://collison.netlify.app"
languageCode = "en-us"
title = "shubham"
sectionPagesMenu = "main"
pluralizelisttitles = false

[permalinks]
  pages = '/:title'

[params]
relativeURLs = true
contentdir = "content"
mobileFriendly = true
fontFamily = "Sree Krushnadevaraya"
fontLink = "ttps://fonts.googleapis.com/css2?family=Sree+Krushnadevaraya&family=VT323&display=swap"
themeColor = "#5998ff"
backgroundColor = "#ffffff"
specialColor = "darkblue"


[menu]

[[menu.pages]]
  name = 'about'
  url = '/about'

[[menu.pages]]
  name = 'blog'
  url = '/blog'

[[menu.pages]]
  name = 'bookshelf'
  url = '/bookshelf'

[[menu.pages]]
  name = 'culture'
  url = '/culture'

[[menu.pages]]
  name = 'links'
  url = '/links'

[[menu.pages]]
  name = 'now'
  url = '/fast'

[[menu.pages]]
  name = 'contact'
  url = '/questions'

[[menu.pages]]
  name = 'work'
  url = '/work'

[[menu.pages]]
  name = 'colophon'
  url = '/work'
